[platformio]
data_dir = data

[env:lolin_s2_mini]
platform = espressif32@6.5.0
framework = arduino
board = lolin_s2_mini
board_build.f_cpu = 240000000L

; Включаем поддержку встроенного USB-порта для вывода в Serial Monitor
build_flags = 
    -D MQTT_MAX_PACKET_SIZE=2048
    -D CORE_DEBUG_LEVEL=4
    -D _DEBUG
    -D ARDUINO_USB_CDC_ON_BOOT=1
    --after no_reset ; <-- ДОБАВЬТЕ ЭТУ СТРОКУ (прикажет esptool не делать ресет по USB)

board_build.filesystem = littlefs

lib_deps = 
    adafruit/Adafruit GFX Library @ ^1.11.9
    adafruit/Adafruit BusIO @ ^1.14.5
    adafruit/Adafruit SSD1306 @ ^2.5.13
    knolleary/PubSubClient @ ^2.8

;команда для сборки кода и структуры
;$outFile = "all_code.txt"; Remove-Item -ErrorAction Ignore $outFile; $treeStr = "`n// ==================== СТРУКТУРА ПРОЕКТА ====================`n"; [System.IO.File]::AppendAllText($outFile, $treeStr, [System.Text.Encoding]::UTF8); Get-ChildItem -Recurse -Exclude ".*","all_code.txt" | Where-Object { $_.FullName -notmatch '\\\.' } | ForEach-Object { $indent = ""; $pathParts = $_.FullName.Replace((Get-Location).Path, "").Split([System.IO.Path]::DirectorySeparatorChar); for($i=1; $i -lt $pathParts.Length; $i++) { $indent += "  " }; $line = $indent + "- " + $_.Name + "`n"; [System.IO.File]::AppendAllText($outFile, $line, [System.Text.Encoding]::UTF8) }; Get-ChildItem -Path "src\*", "platformio.ini" -Include *.cpp, *.h, *.ini | ForEach-Object { $divider = "`n`n// ==================== FILE: " + $_.Name + " ====================`n"; [System.IO.File]::AppendAllText($outFile, $divider, [System.Text.Encoding]::UTF8); $content = [System.IO.File]::ReadAllText($_.FullName, [System.Text.Encoding]::UTF8); [System.IO.File]::AppendAllText($outFile, $content, [System.Text.Encoding]::UTF8) }
